export const eventPhotos = [
 {id:'gala',url:'https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972657/11_imp_cover_page_umrvw4.jpg',title:'Celebrity gala & red carpet',category:'Celebrity gatherings',description:'Imran Mirza with guests and industry dignitaries.'},
 {id:'awards',url:'https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972673/DSC_0634_l5nc6v.jpg',title:'An evening of recognition',category:'Awards & celebrations',description:'People, recognition and memorable celebrations.'},
 {id:'guests',url:'https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972656/16_pi03mq.jpg',title:'Distinguished company',category:'Celebrity gatherings',description:'Moments with guests from the world of entertainment.'},
 {id:'stage',url:'https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972672/DSC_0632_lvbvde.jpg',title:'In the spotlight',category:'Awards & celebrations',description:'A look inside the Pan Eventz archive.'}
];
export const eventServices = [
 {slug:'corporate',title:'Corporate events',subtitle:'Make your brand the occasion.',description:'Conferences, summits, annual meetings and company milestones. From the first invitation to the final presentation, we bring strategy, hospitality and production together.',details:'Conferences / Enterprise Summits / Annual Celebrations'},
 {slug:'wedding',title:'Weddings & celebrations',subtitle:'Personal stories. Unforgettable occasions.',description:'Royal destination weddings, thoughtful décor, stage design and guest hospitality, brought together around your traditions, your families and your celebration.',details:'Wedding Planning / Palatial Décor / Guest Experiences'},
 {slug:'live-entertainment',title:'Live entertainment',subtitle:'For the energy of the crowd.',description:'Arena concerts, stadium sports spectacles and live headline entertainment supported by German line-array audio, dynamic lighting and live broadcast coverage.',details:'Concerts / Stadium Arenas / Artist Management'},
 {slug:'awards-launches',title:'Awards & launches',subtitle:'Make headlines. Honor achievements.',description:'Prestigious award ceremonies, theatrical product unveils and high-profile brand reveals designed with red-carpet hospitality and stagecraft.',details:'Award Galas / Product Reveals / Keynote Showcases'},
 {slug:'private-experiences',title:'Private experiences',subtitle:'Discreet, intimate, extraordinary.',description:'Bespoke milestone celebrations, private estate gatherings and sovereign soirees executed with absolute discretion, personalized culinary staging and perfection.',details:'Private Dinners / Milestone Celebrations / VIP Soirées'}
];
