export type EventPhoto = {
  id: string;
  publicId: string;
  url: string;
  thumbnailUrl: string;
  title: string;
  category: string;
  description: string;
  width: number;
  height: number;
  orientation: 'portrait' | 'landscape';
};

export const eventPhotos: EventPhoto[] = [
  {
    "id": "11-imp-cover-page-umrvw4",
    "publicId": "11_imp_cover_page_umrvw4",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972657/11_imp_cover_page_umrvw4.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972657/11_imp_cover_page_umrvw4.jpg",
    "title": "Celebrity gala & red carpet",
    "category": "Celebrity moments",
    "description": "Imran Mirza with guests and industry dignitaries.",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "dsc-0634-l5nc6v",
    "publicId": "DSC_0634_l5nc6v",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972673/DSC_0634_l5nc6v.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972673/DSC_0634_l5nc6v.jpg",
    "title": "An evening of recognition",
    "category": "Celebrity moments",
    "description": "People, recognition and memorable celebrations.",
    "width": 1200,
    "height": 800,
    "orientation": "landscape"
  },
  {
    "id": "16-pi03mq",
    "publicId": "16_pi03mq",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972656/16_pi03mq.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972656/16_pi03mq.jpg",
    "title": "Distinguished company",
    "category": "Celebrity moments",
    "description": "Moments with guests from the world of entertainment.",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "dsc-0632-lvbvde",
    "publicId": "DSC_0632_lvbvde",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972672/DSC_0632_lvbvde.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972672/DSC_0632_lvbvde.jpg",
    "title": "In the spotlight",
    "category": "Celebrity moments",
    "description": "A look inside the Pan Eventz archive.",
    "width": 1200,
    "height": 800,
    "orientation": "landscape"
  },
  {
    "id": "5-sga7d9-a-90-lyxiir",
    "publicId": "5_sga7d9_a_90_lyxiir",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1752585576/5_sga7d9_a_90_lyxiir.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1752585576/5_sga7d9_a_90_lyxiir.jpg",
    "title": "Pan Eventz archive 5 sga7d9 a 90",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "dscn6132-volru9",
    "publicId": "DSCN6132_volru9",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973247/DSCN6132_volru9.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973247/DSCN6132_volru9.jpg",
    "title": "Event moment DSCN6132",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5152,
    "height": 3864,
    "orientation": "landscape"
  },
  {
    "id": "dscn6119-wl6b3k",
    "publicId": "DSCN6119_wl6b3k",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973244/DSCN6119_wl6b3k.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973244/DSCN6119_wl6b3k.jpg",
    "title": "Event moment DSCN6119",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5152,
    "height": 3864,
    "orientation": "landscape"
  },
  {
    "id": "dscn6120-iyoxfy",
    "publicId": "DSCN6120_iyoxfy",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973244/DSCN6120_iyoxfy.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973244/DSCN6120_iyoxfy.jpg",
    "title": "Event moment DSCN6120",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5152,
    "height": 3864,
    "orientation": "landscape"
  },
  {
    "id": "dscn6113-end0yr",
    "publicId": "DSCN6113_end0yr",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973237/DSCN6113_end0yr.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973237/DSCN6113_end0yr.jpg",
    "title": "Event moment DSCN6113",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5152,
    "height": 3864,
    "orientation": "landscape"
  },
  {
    "id": "dsc-1317-dmjga7",
    "publicId": "DSC_1317_dmjga7",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973053/DSC_1317_dmjga7.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973053/DSC_1317_dmjga7.jpg",
    "title": "Event moment DSC 1317",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4928,
    "height": 3264,
    "orientation": "landscape"
  },
  {
    "id": "dsc-1463-jvapcc",
    "publicId": "DSC_1463_jvapcc",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973042/DSC_1463_jvapcc.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973042/DSC_1463_jvapcc.jpg",
    "title": "Event moment DSC 1463",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3696,
    "height": 2448,
    "orientation": "landscape"
  },
  {
    "id": "img-7207-denx8g",
    "publicId": "IMG_7207_denx8g",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972997/IMG_7207_denx8g.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972997/IMG_7207_denx8g.jpg",
    "title": "Guest experience IMG 7207",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "img-7172-lt7l3d",
    "publicId": "IMG_7172_lt7l3d",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972996/IMG_7172_lt7l3d.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972996/IMG_7172_lt7l3d.jpg",
    "title": "Guest experience IMG 7172",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "img-7189-fpdzil",
    "publicId": "IMG_7189_fpdzil",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972990/IMG_7189_fpdzil.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972990/IMG_7189_fpdzil.jpg",
    "title": "Guest experience IMG 7189",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "img-7132-vshgsj",
    "publicId": "IMG_7132_vshgsj",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972980/IMG_7132_vshgsj.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972980/IMG_7132_vshgsj.jpg",
    "title": "Guest experience IMG 7132",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "4-u7tr0a",
    "publicId": "4_u7tr0a",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972957/4_u7tr0a.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972957/4_u7tr0a.jpg",
    "title": "Pan Eventz archive 4",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "4-2-zzywd6",
    "publicId": "4_2_zzywd6",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972956/4_2_zzywd6.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972956/4_2_zzywd6.jpg",
    "title": "Pan Eventz archive 4 2",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "3-pmtwdu",
    "publicId": "3_pmtwdu",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972946/3_pmtwdu.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972946/3_pmtwdu.jpg",
    "title": "Pan Eventz archive 3",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "3-2-kixykn",
    "publicId": "3_2_kixykn",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972943/3_2_kixykn.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972943/3_2_kixykn.jpg",
    "title": "Pan Eventz archive 3 2",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "2-2-mkan6t",
    "publicId": "2_2_mkan6t",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972943/2_2_mkan6t.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972943/2_2_mkan6t.jpg",
    "title": "Pan Eventz archive 2 2",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "1-xi6ddr",
    "publicId": "1_xi6ddr",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972941/1_xi6ddr.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972941/1_xi6ddr.jpg",
    "title": "Pan Eventz archive 1",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "1-2-mjibcj",
    "publicId": "1_2_mjibcj",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972939/1_2_mjibcj.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972939/1_2_mjibcj.jpg",
    "title": "Pan Eventz archive 1 2",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "dscn6130-copy-tw0skj",
    "publicId": "DSCN6130_-_Copy_tw0skj",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972919/DSCN6130_-_Copy_tw0skj.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972919/DSCN6130_-_Copy_tw0skj.jpg",
    "title": "Event moment DSCN6130",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5152,
    "height": 3864,
    "orientation": "landscape"
  },
  {
    "id": "img-0680-copy-bffyqy",
    "publicId": "IMG_0680_-_Copy_bffyqy",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972914/IMG_0680_-_Copy_bffyqy.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972914/IMG_0680_-_Copy_bffyqy.jpg",
    "title": "Guest experience IMG 0680",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "8x12-1-copy-idmnnn",
    "publicId": "8x12_1_-_Copy_idmnnn",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972912/8x12_1_-_Copy_idmnnn.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972912/8x12_1_-_Copy_idmnnn.jpg",
    "title": "Pan Eventz archive 8x12 1",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3000,
    "height": 2000,
    "orientation": "landscape"
  },
  {
    "id": "8x12-2-copy-gcl5ik",
    "publicId": "8x12_2_-_Copy_gcl5ik",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972910/8x12_2_-_Copy_gcl5ik.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972910/8x12_2_-_Copy_gcl5ik.jpg",
    "title": "Pan Eventz archive 8x12 2",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3000,
    "height": 2000,
    "orientation": "landscape"
  },
  {
    "id": "img-0409-copy-d0vlre",
    "publicId": "IMG_0409_-_Copy_d0vlre",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972908/IMG_0409_-_Copy_d0vlre.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972908/IMG_0409_-_Copy_d0vlre.jpg",
    "title": "Guest experience IMG 0409",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4368,
    "height": 2912,
    "orientation": "landscape"
  },
  {
    "id": "img-0293-copy-p3pmsl",
    "publicId": "IMG_0293_-_Copy_p3pmsl",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972907/IMG_0293_-_Copy_p3pmsl.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972907/IMG_0293_-_Copy_p3pmsl.jpg",
    "title": "Guest experience IMG 0293",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4368,
    "height": 2912,
    "orientation": "landscape"
  },
  {
    "id": "uvs110325-001-aaohmz",
    "publicId": "uvs110325-001_aaohmz",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972906/uvs110325-001_aaohmz.bmp",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972906/uvs110325-001_aaohmz.bmp",
    "title": "Uvs110325 001",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 720,
    "height": 576,
    "orientation": "landscape"
  },
  {
    "id": "img-0295-copy-al63qu",
    "publicId": "IMG_0295_-_Copy_al63qu",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972905/IMG_0295_-_Copy_al63qu.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972905/IMG_0295_-_Copy_al63qu.jpg",
    "title": "Guest experience IMG 0295",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4368,
    "height": 2912,
    "orientation": "landscape"
  },
  {
    "id": "imga0686-hzel1m",
    "publicId": "IMGA0686_hzel1m",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972905/IMGA0686_hzel1m.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972905/IMGA0686_hzel1m.jpg",
    "title": "Guest experience IMGA0686",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1760,
    "height": 1320,
    "orientation": "landscape"
  },
  {
    "id": "image0222-copy-lsh882",
    "publicId": "Image0222_-_Copy_lsh882",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972904/Image0222_-_Copy_lsh882.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972904/Image0222_-_Copy_lsh882.jpg",
    "title": "Image0222",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "imga0865-f6okqc",
    "publicId": "IMGA0865_f6okqc",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972902/IMGA0865_f6okqc.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972902/IMGA0865_f6okqc.jpg",
    "title": "Guest experience IMGA0865",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 640,
    "height": 480,
    "orientation": "landscape"
  },
  {
    "id": "1384943207372-copy-fe6eto",
    "publicId": "1384943207372_-_Copy_fe6eto",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972901/1384943207372_-_Copy_fe6eto.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972901/1384943207372_-_Copy_fe6eto.jpg",
    "title": "Pan Eventz archive 1384943207372",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 408,
    "height": 306,
    "orientation": "landscape"
  },
  {
    "id": "20160421-133313-vgceat",
    "publicId": "20160421_133313_vgceat",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972886/20160421_133313_vgceat.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972886/20160421_133313_vgceat.jpg",
    "title": "Pan Eventz archive 20160421 133313",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2448,
    "height": 3264,
    "orientation": "portrait"
  },
  {
    "id": "1-fub82o",
    "publicId": "1_fub82o",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972880/1_fub82o.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972880/1_fub82o.jpg",
    "title": "Pan Eventz archive 1",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f200192608-z4mhuh",
    "publicId": "f200192608_z4mhuh",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972872/f200192608_z4mhuh.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972872/f200192608_z4mhuh.jpg",
    "title": "F200192608",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f200226784-pq10kk",
    "publicId": "f200226784_pq10kk",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972871/f200226784_pq10kk.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972871/f200226784_pq10kk.jpg",
    "title": "F200226784",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "gpa-3824-mixitw",
    "publicId": "GPA_3824_mixitw",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972826/GPA_3824_mixitw.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972826/GPA_3824_mixitw.jpg",
    "title": "GPA 3824",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f208044992-iesusm",
    "publicId": "f208044992_iesusm",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972817/f208044992_iesusm.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972817/f208044992_iesusm.jpg",
    "title": "F208044992",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f207429248-bfz8pl",
    "publicId": "f207429248_bfz8pl",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972817/f207429248_bfz8pl.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972817/f207429248_bfz8pl.jpg",
    "title": "F207429248",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f200511040-kssf8m",
    "publicId": "f200511040_kssf8m",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972812/f200511040_kssf8m.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972812/f200511040_kssf8m.jpg",
    "title": "F200511040",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f200597280-xu5fxn",
    "publicId": "f200597280_xu5fxn",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972811/f200597280_xu5fxn.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972811/f200597280_xu5fxn.jpg",
    "title": "F200597280",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f207696672-bo5mui",
    "publicId": "f207696672_bo5mui",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972804/f207696672_bo5mui.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972804/f207696672_bo5mui.jpg",
    "title": "F207696672",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f207986944-dt2gez",
    "publicId": "f207986944_dt2gez",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972803/f207986944_dt2gez.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972803/f207986944_dt2gez.jpg",
    "title": "F207986944",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "f200297312-us0tue",
    "publicId": "f200297312_us0tue",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972800/f200297312_us0tue.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972800/f200297312_us0tue.jpg",
    "title": "F200297312",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5760,
    "height": 3840,
    "orientation": "landscape"
  },
  {
    "id": "4-h49llq",
    "publicId": "4_h49llq",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972766/4_h49llq.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972766/4_h49llq.jpg",
    "title": "Pan Eventz archive 4",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "7-bmgaqq",
    "publicId": "7_bmgaqq",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972765/7_bmgaqq.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972765/7_bmgaqq.jpg",
    "title": "Pan Eventz archive 7",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "6-nzi95h",
    "publicId": "6_nzi95h",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972765/6_nzi95h.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972765/6_nzi95h.jpg",
    "title": "Pan Eventz archive 6",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "8-ihsgez",
    "publicId": "8_ihsgez",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972760/8_ihsgez.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972760/8_ihsgez.jpg",
    "title": "Pan Eventz archive 8",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "3-ulnfv4",
    "publicId": "3_ulnfv4",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972753/3_ulnfv4.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972753/3_ulnfv4.jpg",
    "title": "Pan Eventz archive 3",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0626-a9u0ew",
    "publicId": "DSC_0626_a9u0ew",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972672/DSC_0626_a9u0ew.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972672/DSC_0626_a9u0ew.jpg",
    "title": "Event moment DSC 0626",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3216,
    "height": 2136,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0630-altd3c",
    "publicId": "DSC_0630_altd3c",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972672/DSC_0630_altd3c.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972672/DSC_0630_altd3c.jpg",
    "title": "Event moment DSC 0630",
    "category": "Celebrity moments",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3216,
    "height": 2136,
    "orientation": "landscape"
  },
  {
    "id": "13-tjwcyz",
    "publicId": "13_tjwcyz",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972667/13_tjwcyz.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972667/13_tjwcyz.jpg",
    "title": "Pan Eventz archive 13",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1050,
    "height": 750,
    "orientation": "landscape"
  },
  {
    "id": "15-dsakdb",
    "publicId": "15_dsakdb",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972666/15_dsakdb.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972666/15_dsakdb.jpg",
    "title": "Pan Eventz archive 15",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1280,
    "height": 960,
    "orientation": "landscape"
  },
  {
    "id": "img-20150629-wa0017-i0adlw",
    "publicId": "IMG-20150629-WA0017_i0adlw",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972666/IMG-20150629-WA0017_i0adlw.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972666/IMG-20150629-WA0017_i0adlw.jpg",
    "title": "Guest experience IMG 20150629 WA0017",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 880,
    "height": 660,
    "orientation": "landscape"
  },
  {
    "id": "img-20150418-wa0005-gcc7fx",
    "publicId": "IMG-20150418-WA0005_gcc7fx",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972664/IMG-20150418-WA0005_gcc7fx.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972664/IMG-20150418-WA0005_gcc7fx.jpg",
    "title": "Guest experience IMG 20150418 WA0005",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1280,
    "height": 960,
    "orientation": "landscape"
  },
  {
    "id": "img-20150324-wa0001-bxmpfh",
    "publicId": "IMG-20150324-WA0001_bxmpfh",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972663/IMG-20150324-WA0001_bxmpfh.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972663/IMG-20150324-WA0001_bxmpfh.jpg",
    "title": "Guest experience IMG 20150324 WA0001",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 640,
    "height": 512,
    "orientation": "landscape"
  },
  {
    "id": "img-20150322-wa0014-nkqe8z",
    "publicId": "IMG-20150322-WA0014_nkqe8z",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972662/IMG-20150322-WA0014_nkqe8z.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972662/IMG-20150322-WA0014_nkqe8z.jpg",
    "title": "Guest experience IMG 20150322 WA0014",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 640,
    "height": 480,
    "orientation": "landscape"
  },
  {
    "id": "22-fqse8z",
    "publicId": "22_fqse8z",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972658/22_fqse8z.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972658/22_fqse8z.jpg",
    "title": "Pan Eventz archive 22",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 750,
    "height": 500,
    "orientation": "landscape"
  },
  {
    "id": "img-20150629-wa0028-anscj4",
    "publicId": "IMG-20150629-WA0028_anscj4",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972652/IMG-20150629-WA0028_anscj4.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972652/IMG-20150629-WA0028_anscj4.jpg",
    "title": "Guest experience IMG 20150629 WA0028",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 816,
    "height": 612,
    "orientation": "landscape"
  },
  {
    "id": "9-raxrwf",
    "publicId": "9_raxrwf",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972651/9_raxrwf.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972651/9_raxrwf.jpg",
    "title": "Pan Eventz archive 9",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1280,
    "height": 960,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0733-xxespx",
    "publicId": "DSC_0733_xxespx",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972622/DSC_0733_xxespx.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972622/DSC_0733_xxespx.jpg",
    "title": "Event moment DSC 0733",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3872,
    "height": 2592,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0732-k9eoya",
    "publicId": "DSC_0732_k9eoya",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972620/DSC_0732_k9eoya.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972620/DSC_0732_k9eoya.jpg",
    "title": "Event moment DSC 0732",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3872,
    "height": 2592,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0663-htgksj",
    "publicId": "DSC_0663_htgksj",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972617/DSC_0663_htgksj.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972617/DSC_0663_htgksj.jpg",
    "title": "Event moment DSC 0663",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3872,
    "height": 2592,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0812-faei64",
    "publicId": "DSC_0812_faei64",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972616/DSC_0812_faei64.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972616/DSC_0812_faei64.jpg",
    "title": "Event moment DSC 0812",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3872,
    "height": 2592,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0167-mnzm0c",
    "publicId": "DSC_0167_mnzm0c",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972615/DSC_0167_mnzm0c.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972615/DSC_0167_mnzm0c.jpg",
    "title": "Event moment DSC 0167",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2896,
    "height": 1944,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0454-biaryd",
    "publicId": "DSC_0454_biaryd",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972612/DSC_0454_biaryd.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972612/DSC_0454_biaryd.jpg",
    "title": "Event moment DSC 0454",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3872,
    "height": 2592,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0842-wchpfv",
    "publicId": "DSC_0842_wchpfv",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972612/DSC_0842_wchpfv.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972612/DSC_0842_wchpfv.jpg",
    "title": "Event moment DSC 0842",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3216,
    "height": 2136,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0142-njsmtv",
    "publicId": "DSC_0142_njsmtv",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972610/DSC_0142_njsmtv.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972610/DSC_0142_njsmtv.jpg",
    "title": "Event moment DSC 0142",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2896,
    "height": 1944,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0070-blphpr",
    "publicId": "DSC_0070_blphpr",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972606/DSC_0070_blphpr.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972606/DSC_0070_blphpr.jpg",
    "title": "Event moment DSC 0070",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2896,
    "height": 1944,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0219-xdh2x9",
    "publicId": "DSC_0219_xdh2x9",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972606/DSC_0219_xdh2x9.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972606/DSC_0219_xdh2x9.jpg",
    "title": "Event moment DSC 0219",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3216,
    "height": 2136,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0014-at8ph4",
    "publicId": "DSC_0014_at8ph4",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972606/DSC_0014_at8ph4.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972606/DSC_0014_at8ph4.jpg",
    "title": "Event moment DSC 0014",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3216,
    "height": 2136,
    "orientation": "landscape"
  },
  {
    "id": "1-2-exggap",
    "publicId": "1_2_exggap",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972551/1_2_exggap.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972551/1_2_exggap.jpg",
    "title": "Pan Eventz archive 1 2",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3696,
    "height": 2448,
    "orientation": "landscape"
  },
  {
    "id": "3-2-dse6fr",
    "publicId": "3_2_dse6fr",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972541/3_2_dse6fr.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972541/3_2_dse6fr.jpg",
    "title": "Pan Eventz archive 3 2",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 3696,
    "height": 2448,
    "orientation": "landscape"
  },
  {
    "id": "3-phoctn",
    "publicId": "3_phoctn",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972541/3_phoctn.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972541/3_phoctn.jpg",
    "title": "Pan Eventz archive 3",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4496,
    "height": 3000,
    "orientation": "landscape"
  },
  {
    "id": "216-sof48q",
    "publicId": "216_sof48q",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972519/216_sof48q.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972519/216_sof48q.jpg",
    "title": "Pan Eventz archive 216",
    "category": "Celebrity moments",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2736,
    "height": 4104,
    "orientation": "portrait"
  },
  {
    "id": "221-drooq8",
    "publicId": "221_drooq8",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972518/221_drooq8.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972518/221_drooq8.jpg",
    "title": "Pan Eventz archive 221",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4103,
    "height": 2418,
    "orientation": "landscape"
  },
  {
    "id": "217-jklpng",
    "publicId": "217_jklpng",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972518/217_jklpng.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972518/217_jklpng.jpg",
    "title": "Pan Eventz archive 217",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2736,
    "height": 4104,
    "orientation": "portrait"
  },
  {
    "id": "1-wpodc0",
    "publicId": "1_wpodc0",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972517/1_wpodc0.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972517/1_wpodc0.jpg",
    "title": "Pan Eventz archive 1",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4104,
    "height": 2736,
    "orientation": "landscape"
  },
  {
    "id": "2-pxvu9w",
    "publicId": "2_pxvu9w",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972517/2_pxvu9w.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972517/2_pxvu9w.jpg",
    "title": "Pan Eventz archive 2",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4104,
    "height": 2736,
    "orientation": "landscape"
  },
  {
    "id": "66-d1ldjf",
    "publicId": "66_d1ldjf",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972477/66_d1ldjf.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972477/66_d1ldjf.jpg",
    "title": "Pan Eventz archive 66",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "6-yptxj9",
    "publicId": "6_yptxj9",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972475/6_yptxj9.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972475/6_yptxj9.jpg",
    "title": "Pan Eventz archive 6",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "2-ng99mw",
    "publicId": "2_ng99mw",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972475/2_ng99mw.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972475/2_ng99mw.jpg",
    "title": "Pan Eventz archive 2",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "5-clqdnq",
    "publicId": "5_clqdnq",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972475/5_clqdnq.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972475/5_clqdnq.jpg",
    "title": "Pan Eventz archive 5",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "8-vrcbwn",
    "publicId": "8_vrcbwn",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972474/8_vrcbwn.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972474/8_vrcbwn.jpg",
    "title": "Pan Eventz archive 8",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "7-fmorwv",
    "publicId": "7_fmorwv",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972474/7_fmorwv.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972474/7_fmorwv.jpg",
    "title": "Pan Eventz archive 7",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "3-yttqpu",
    "publicId": "3_yttqpu",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972474/3_yttqpu.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972474/3_yttqpu.jpg",
    "title": "Pan Eventz archive 3",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "1-vgqlb9",
    "publicId": "1_vgqlb9",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972473/1_vgqlb9.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972473/1_vgqlb9.jpg",
    "title": "Pan Eventz archive 1",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "5-mqiqpm",
    "publicId": "5_mqiqpm",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972368/5_mqiqpm.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972368/5_mqiqpm.jpg",
    "title": "Pan Eventz archive 5",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "4-m3fimh",
    "publicId": "4_m3fimh",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972367/4_m3fimh.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972367/4_m3fimh.jpg",
    "title": "Pan Eventz archive 4",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 2592,
    "height": 1728,
    "orientation": "landscape"
  },
  {
    "id": "9-l0mfkd",
    "publicId": "9_l0mfkd",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972338/9_l0mfkd.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972338/9_l0mfkd.jpg",
    "title": "Pan Eventz archive 9",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "8-ucaiuq",
    "publicId": "8_ucaiuq",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972338/8_ucaiuq.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972338/8_ucaiuq.jpg",
    "title": "Pan Eventz archive 8",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "7-uwskmk",
    "publicId": "7_uwskmk",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972337/7_uwskmk.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972337/7_uwskmk.jpg",
    "title": "Pan Eventz archive 7",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "6-ghtq2p",
    "publicId": "6_ghtq2p",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972337/6_ghtq2p.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972337/6_ghtq2p.jpg",
    "title": "Pan Eventz archive 6",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "5-iqzxbi",
    "publicId": "5_iqzxbi",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972336/5_iqzxbi.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972336/5_iqzxbi.jpg",
    "title": "Pan Eventz archive 5",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "4-dciwz3",
    "publicId": "4_dciwz3",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972336/4_dciwz3.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972336/4_dciwz3.jpg",
    "title": "Pan Eventz archive 4",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "3-w50ioy",
    "publicId": "3_w50ioy",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972336/3_w50ioy.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972336/3_w50ioy.jpg",
    "title": "Pan Eventz archive 3",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "2-trhg4n",
    "publicId": "2_trhg4n",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972336/2_trhg4n.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972336/2_trhg4n.jpg",
    "title": "Pan Eventz archive 2",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "1-kw9k5u",
    "publicId": "1_kw9k5u",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972335/1_kw9k5u.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972335/1_kw9k5u.jpg",
    "title": "Pan Eventz archive 1",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "6-hafkyj",
    "publicId": "6_hafkyj",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972276/6_hafkyj.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972276/6_hafkyj.jpg",
    "title": "Pan Eventz archive 6",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "4-qmmwd8",
    "publicId": "4_qmmwd8",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972276/4_qmmwd8.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972276/4_qmmwd8.jpg",
    "title": "Pan Eventz archive 4",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "2-pdj77d",
    "publicId": "2_pdj77d",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972276/2_pdj77d.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972276/2_pdj77d.jpg",
    "title": "Pan Eventz archive 2",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "3-wkbi0r",
    "publicId": "3_wkbi0r",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972276/3_wkbi0r.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972276/3_wkbi0r.jpg",
    "title": "Pan Eventz archive 3",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  },
  {
    "id": "1-nzcnpk",
    "publicId": "1_nzcnpk",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972276/1_nzcnpk.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972276/1_nzcnpk.jpg",
    "title": "Pan Eventz archive 1",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 1600,
    "height": 1200,
    "orientation": "landscape"
  }
];

export const featuredEventPhotos: EventPhoto[] = [
  {
    "id": "11-imp-cover-page-umrvw4",
    "publicId": "11_imp_cover_page_umrvw4",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972657/11_imp_cover_page_umrvw4.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972657/11_imp_cover_page_umrvw4.jpg",
    "title": "Celebrity gala & red carpet",
    "category": "Celebrity moments",
    "description": "Imran Mirza with guests and industry dignitaries.",
    "width": 1200,
    "height": 1600,
    "orientation": "portrait"
  },
  {
    "id": "dsc-0634-l5nc6v",
    "publicId": "DSC_0634_l5nc6v",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972673/DSC_0634_l5nc6v.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972673/DSC_0634_l5nc6v.jpg",
    "title": "An evening of recognition",
    "category": "Celebrity moments",
    "description": "People, recognition and memorable celebrations.",
    "width": 1200,
    "height": 800,
    "orientation": "landscape"
  },
  {
    "id": "dsc-0632-lvbvde",
    "publicId": "DSC_0632_lvbvde",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972672/DSC_0632_lvbvde.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972672/DSC_0632_lvbvde.jpg",
    "title": "In the spotlight",
    "category": "Celebrity moments",
    "description": "A look inside the Pan Eventz archive.",
    "width": 1200,
    "height": 800,
    "orientation": "landscape"
  },
  {
    "id": "dscn6132-volru9",
    "publicId": "DSCN6132_volru9",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973247/DSCN6132_volru9.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973247/DSCN6132_volru9.jpg",
    "title": "Event moment DSCN6132",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5152,
    "height": 3864,
    "orientation": "landscape"
  },
  {
    "id": "dsc-1317-dmjga7",
    "publicId": "DSC_1317_dmjga7",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749973053/DSC_1317_dmjga7.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749973053/DSC_1317_dmjga7.jpg",
    "title": "Event moment DSC 1317",
    "category": "Corporate productions",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4928,
    "height": 3264,
    "orientation": "landscape"
  },
  {
    "id": "img-7207-denx8g",
    "publicId": "IMG_7207_denx8g",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972997/IMG_7207_denx8g.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972997/IMG_7207_denx8g.jpg",
    "title": "Guest experience IMG 7207",
    "category": "Community events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "img-7172-lt7l3d",
    "publicId": "IMG_7172_lt7l3d",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972996/IMG_7172_lt7l3d.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972996/IMG_7172_lt7l3d.jpg",
    "title": "Guest experience IMG 7172",
    "category": "Signature events",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 5184,
    "height": 3456,
    "orientation": "landscape"
  },
  {
    "id": "img-0409-copy-d0vlre",
    "publicId": "IMG_0409_-_Copy_d0vlre",
    "url": "https://res.cloudinary.com/dhxetyrkb/image/upload/v1749972908/IMG_0409_-_Copy_d0vlre.jpg",
    "thumbnailUrl": "https://res.cloudinary.com/dhxetyrkb/image/upload/f_auto,q_auto:good,w_900,c_limit/v1749972908/IMG_0409_-_Copy_d0vlre.jpg",
    "title": "Guest experience IMG 0409",
    "category": "Live production",
    "description": "A real Pan Eventz moment from the Cloudinary archive, preserved as part of the brand story.",
    "width": 4368,
    "height": 2912,
    "orientation": "landscape"
  }
];

export const eventPhotoCategories = [
  "All moments",
  "Celebrity moments",
  "Signature events",
  "Live production",
  "Corporate productions",
  "Community events"
];

export const eventServices = [
 {slug:'corporate',title:'Corporate events',subtitle:'Make your brand the occasion.',description:'Conferences, summits, annual meetings and company milestones. From the first invitation to the final presentation, we bring strategy, hospitality and production together.',details:'Conferences / Enterprise Summits / Annual Celebrations'},
 {slug:'wedding',title:'Weddings & celebrations',subtitle:'Personal stories. Unforgettable occasions.',description:'Royal destination weddings, thoughtful décor, stage design and guest hospitality, brought together around your traditions, your families and your celebration.',details:'Wedding Planning / Palatial Décor / Guest Experiences'},
 {slug:'live-entertainment',title:'Live entertainment',subtitle:'For the energy of the crowd.',description:'Arena concerts, stadium sports spectacles and live headline entertainment supported by German line-array audio, dynamic lighting and live broadcast coverage.',details:'Concerts / Stadium Arenas / Artist Management'},
 {slug:'awards-launches',title:'Awards & launches',subtitle:'Make headlines. Honor achievements.',description:'Prestigious award ceremonies, theatrical product unveils and high-profile brand reveals designed with red-carpet hospitality and stagecraft.',details:'Award Galas / Product Reveals / Keynote Showcases'},
 {slug:'private-experiences',title:'Private experiences',subtitle:'Discreet, intimate, extraordinary.',description:'Bespoke milestone celebrations, private estate gatherings and sovereign soirees executed with absolute discretion, personalized culinary staging and perfection.',details:'Private Dinners / Milestone Celebrations / VIP Soirées'}
];
